name: CD-Staging

on:
  push:
    branches: [ develop ]

env:
  IMAGE_NAME: staging-web-beenger

jobs:
  build_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/ryok90/${{ env.IMAGE_NAME }}:latest

      - name: Generate release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true

  deploy:
    needs: build_push
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: SSH to pull image and run
        uses: appleboy/ssh-action@master
        with:
          host: staging.beenger.com
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.ENV_STAGING }}" > .env.${{ env.IMAGE_NAME }}
            docker pull ghcr.io/ryok90/${{ env.IMAGE_NAME }}:latest
            docker stop ${{ env.IMAGE_NAME }}
            docker rm ${{ env.IMAGE_NAME }}
            docker run --env-file=.env.${{ env.IMAGE_NAME }} -p 3021:80 --name ${{ env.IMAGE_NAME }} -d ghcr.io/ryok90/${{ env.IMAGE_NAME }}
            docker image prune -f
