name: CI

on:
  pull_request:
    branches: [ develop, main ]

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
